# -*- coding: utf-8 -*-
"""Activity1: Intro to AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibJC9EKA0QqebijPDTUjpT0KH20i3I4r
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_diabetes
data = load_diabetes(as_frame=True)

df_d = data['data']
df_d['target'] = data['target']

print ('The features are:', data.feature_names)

df_d = data.frame
df_d

feature = df_d.columns[2]

plt.figure(figsize=(10,6))
sns.regplot(x=df_d[feature], y=df_d['target'], line_kws={"color": "red"})

plt.scatter(x=df_d[feature], y=df_d['target'])
plt.title(feature)
plt.ylabel('Diabetes Progression')
plt.xlabel(feature)
plt.show()

fig, axes = plt.subplots(2,5, figsize=(20,10), sharey=True)
cols = df_d.columns[:-1]

for i, ax in enumerate(axes.flatten()):
    ax.scatter(x=df_d[cols[i]], y=df_d['target'])
    ax.set_title(str(cols[i]))

fig.text(0.1, 0.5, 'Diabetes Progression', va='center', rotation='vertical')